# must build the project first with node, pnpm, vite
# from the "web" directory of the repo
# put WEB_DEFAULT_API="http://192.168.1.144:9800" into your .env file
# pnpm run install
# pnpm run build
# then serve the build directory as /home/static in the image
# might need an empty httpd.conf file to get it to work

services: 
  cobalt_web:
    image: lipanski/docker-static-website:latest
    restart: unless-stopped
    ports:
      - 9900:3000
    volumes:
    - ~/.local/opt/cobalt_web:/home/static
    - ~/.local/opt/cobalt_web/httpd.conf:/home/static/httpd.conf:ro
