services: 
  cobalt_web:
    image: lipanski/docker-static-website:latest
    restart: unless-stopped
    ports:
      - "9900:3000"
    volumes:
    - /home/mint/.local/opt/cobalt_web:/home/static
    # can just use an empty httpd.conf file here
    - /home/mint/.local/opt/cobalt_web/httpd.conf:/home/static/httpd.conf:ro
