version: "3.9"
services: 
  cobalt_web:
    image: lipanski/docker-static-website:latest
    containter-name: cobalt_web
    restart: unless-stopped
    ports:
      - "9800:3000"
    volumes:
    - /home/mint/.local/opt/cobalt_web:/home/static
