# must build the project first with node, pnpm, vite
# from the "web" directory of the repo
# pnpm run build
# then serve the build directory as /home/static in the image
# might need an empty httpd.conf file to get it to work

services: 
  cobalt_web:
    image: lipanski/docker-static-website:latest
    restart: unless-stopped
    environment:
      DEFAULT_API: http://127.0.0.1:9800
      WEB_DEFAULT_API: http://127.0.0.1:9800
    ports:
      - 9900:3000
    volumes:
    - /home/mint/.local/opt/cobalt_web:/home/static
    - /home/mint/.local/opt/cobalt_web/httpd.conf:/home/static/httpd.conf:ro
