#!/usr/bin/zsh

echo 'Enter streamer id:'
read streamer_id

streamer_id=$(echo $streamer_id | awk -F/ '{print $NF}')
streamer_id=$(echo $streamer_id | sed 's/[^[:alnum:]_\?=]//g')

termux-clipboard-set $(yt-dlp -f "worstaudio" -g https://twitch.tv/$streamer_id)

termux-toast -s "Link copied to clipboard."